### ISSUE TITLE
I can't Install 'autopy' got an error

### ISSUE THREAD

**Issue by SenuraB** [ravigithub19/ai-virtual-mouse#2]
Hi Ravi,
I am not able to import autopy, cause I got an error. Do you have any suggestions?

**Comment by Aresguerre** [comment]
if using python `3.9+` try downgrading to `3.8`
on macos, if you are on 11 `export SYSTEM_VERSION_COMPAT=1`

**Comment by SenuraB** [comment]
Ok, thanks. it is worked
